services: docker
env:
  global:
  - DOCKER_USER: callforamerica
  # DOCKER_PASS
  - secure: "v7GATy7UI8lo8LeEgPs2C22PX61A9TKxsjqINB5jogxxEHcfdLzFWAM7kkESQw+rvwlSUrMUU4396wpewBS1qV4lhqCh2UjxoTsOdnuk5HZyPGMhz/NJohTOlymK2q/5EEzwOkx0dD64cwXYIMyzg5Pd3WeFvGqK1TkzO0HbjzEviGrOmP4QrlpHLtgUTRqQETNulaCHdlZDa+NWAyqKo+rj2Xrqfg73w43wIgQHhqbriQHKJ4PQE1k5r8Zjb7UXJ04oDpN/LbdDPXAJvzJyN+J5JtnpvrXF1UHrs74yQlgYdYo7+AdA99Vkkk0gFd2zM1jo3rmpBVtQl8c2oPlFkqV2TWEkm5wx10Ee0HZuz4bF0/JxA6rupJcR8GYT5K4PeMAc7sZx7XtOditdwG0AcWmM+fXBx8ZnO+8gexqhQtTZMVatrQNk4lCrNpfdxofj4NKChIkEfDZUQDr3ruJ9vZMklC95VyCu1cdn38JQxSxjFgaIjVvYOIFFgkkAdqwtnE/BGlhaVxtbzXUheUvoL1OuR4f99dl4QJ1cwB/Ido2bEgGE9WFQw6TxyI6u7g8ui5XMBlmiaC2cHQQ4gzQPt1CnVVQpP+E6YE3MU7sVy9gZQQ4mkcac4RCCz3+JKkKj/qIRms+Bem4V2um2DM6qQN2KLMvpX9F3r4FU76x5X+8="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "21z2YTUBZyeA1Bf54TdOMNp/z102FqD2CLAyjQZK4piTZT11vcFTOgKKbnzzNLO09mgfNmnkPJQSLuNXqQgxjBS8+osYBSQnMxve8gigDiTnhIjZ8tTZM+g1A5CI07AYCUo7GSOH3X78lD8fdu/NMakh+GB9o/AgH2iCvlZhOWnQ8efh+XJIG6TQTAp0d0bM5WNXWRGad8rPiqwHGmsRF3lwAFzhjHYmTqELmDCX0+LBXRv4FnZf3x1n4C6QpTNY0W7eCqixOP5n+PS36oYskPlQFT0i2Ei8Sc8MUYRb7CWn0pqkbkc/bVRtBu3CnksXCefR5e/lFB90Y+mirSsxVVvU2eacKtLo/lZPZZraiqwZqC9oEpktZex1OrEYl/MjYYRnO5q/+zCQnfsxRw4H8RVd7xwM1zIG2cwRgg8WBDMeCEN1JmFOGxigHwY+2dQjotshnQDpeKoW+k/N8LjHcZcgyAeIb+roTn/R4LKwh9wwABY/6SdZaaidkO4buf3R9aEy4R51VlxLKYD8+VkpuUBaY/cEzXsVEBrxkXswoSgoMESh1GmGuQ0oQorXVGEQdmFJnTAFxTd0cP98hqC7luH7umwDYRT4GAul6Xo1qGI+XYcjRYwM92Oy1v8LA671t9tq5RkfheK9y7mL950zUHsXG/X497kve2ip5fC8ihI="
    on_success: always
    on_failure: always

before_install: source scripts/ci/environment.sh

install: docker build -t $DOCKER_IMAGE .

script: true

after_success: hub-push
