services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "Hs15h7s7JYAKqlv+Tv3YfsKHwaa2oYKqlOFQ6JNaOn68/71TDunRTq6q6an/i6j9pvF6LeLSSqnfEPWqsF9dmf8XHbzKrdM0VqhKzL6T/o1f4Y69NSm60ZqBiHN/y9sFUVW9lBMwada6Y3Cnt2lTSP/Ko9l1W9am7mIMiD/833gvKBHJuj6SLuI2ZTvYtsdxWRfX0S7Wv02KvhGZZlbiQG99XQDDPF/jx2T5yebKXxYlPTiApGq+KM3C26wTjW4ctC18P1i7OhwiYMnsn+hHAQAo7l2vCYvXdASbOSqleVFkrONEiQd4YfSDz9J86rAkSji/N8UIoF9geVfeVtiLFmVntk/5z7Hy7lVpTX/M+6KQK3rAGlkW39bK57f88S/EvNdnoefl33SXWmGv4MIpTXuXqquZ0/C3iY1fp/HdKV6bIRT1GNfDb5Be/7gUfxKse6CCNjxwcjzel3pOJ0+PUVV2gHQilIdGOtDHNzXai49ONnGTly6/U79ZrbqhCoGKtXN/gXWlRZlsvOYZQ3d/SZ9h56bk4wVfnxBV7e2iLVKrtAMHkvUJiFxhkelyIfbyLGQw8VASA4dGeQEYfi4NhZRV8QE+TJemziXXdSDopFB3DeW+tsOce9TD+WexYEqjaLtsfOoRkiV+OC7p5WGT3AcZzotUt8xwFaXPUE4wigI="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "21z2YTUBZyeA1Bf54TdOMNp/z102FqD2CLAyjQZK4piTZT11vcFTOgKKbnzzNLO09mgfNmnkPJQSLuNXqQgxjBS8+osYBSQnMxve8gigDiTnhIjZ8tTZM+g1A5CI07AYCUo7GSOH3X78lD8fdu/NMakh+GB9o/AgH2iCvlZhOWnQ8efh+XJIG6TQTAp0d0bM5WNXWRGad8rPiqwHGmsRF3lwAFzhjHYmTqELmDCX0+LBXRv4FnZf3x1n4C6QpTNY0W7eCqixOP5n+PS36oYskPlQFT0i2Ei8Sc8MUYRb7CWn0pqkbkc/bVRtBu3CnksXCefR5e/lFB90Y+mirSsxVVvU2eacKtLo/lZPZZraiqwZqC9oEpktZex1OrEYl/MjYYRnO5q/+zCQnfsxRw4H8RVd7xwM1zIG2cwRgg8WBDMeCEN1JmFOGxigHwY+2dQjotshnQDpeKoW+k/N8LjHcZcgyAeIb+roTn/R4LKwh9wwABY/6SdZaaidkO4buf3R9aEy4R51VlxLKYD8+VkpuUBaY/cEzXsVEBrxkXswoSgoMESh1GmGuQ0oQorXVGEQdmFJnTAFxTd0cP98hqC7luH7umwDYRT4GAul6Xo1qGI+XYcjRYwM92Oy1v8LA671t9tq5RkfheK9y7mL950zUHsXG/X497kve2ip5fC8ihI="
    on_success: always
    on_failure: always

before_install: source scripts/ci/environment.sh

install: docker build -t $DOCKER_IMAGE .

script: true

after_success:
- ci-tag-build
- hub-push
