language: python
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "NWTMKWc/BYCXz5NQo9uavmzbSco9nU1nPDBg+kyByXLpYCalaDLWQK4NQOWrTfCvXRGvEqOk/5JACsSdo8ei3nkX5nc2RumwLCXnEcFZf8GIPAL/xwVr+qOha9J2GMEAjJ44MXvSvuh108vQaGrAsiNoKO2iHM53ZsV0aAOVRBQkgqhSl1ap+q+shPw+lQJ3CTVGmv9RGjUp4ERwI1l9ZE566Xa4ODwk7esIimvYqB8M64HyiRk/Mm173ZWYDdXIo11+HmbCf1Fld4iyAn0CJMiKcxjMh0euJU943I3qwcS21TNrBaLSvnxK+gSxyzKOLVaDZPhQqCDbUAuNpbvy9shByQfpXoU8eBz8IZRzH2Im4FJM2q0qSGi0uGL7L8TDaRIU4a1s0mHOU+XGhlYxVTg2e82fwbsN38nvNkN0Vyc3ayfEGdHHpNm/jOtzBn+9a+wwkG7zjiMghzue5x+GIuQIHO9OxVucPf1ijkHYp++ZjmklstOP/ma7gxbQVjf29YLVR+2vy7IjFbz0vorbZAMRSeijoORo79Gv0w1fKFt+lUhvnXwA/1ao3I8u1hp1rLqFDK4slcaIiNriDv5gOblaTgtkzo2RxcELZxE1uhxNZNfQ9FMga0SF6+fsD6Ro7Rvsv6mdGmYAJQUm5dvpTZ0C+SK4spkek266fzU4leE="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "21z2YTUBZyeA1Bf54TdOMNp/z102FqD2CLAyjQZK4piTZT11vcFTOgKKbnzzNLO09mgfNmnkPJQSLuNXqQgxjBS8+osYBSQnMxve8gigDiTnhIjZ8tTZM+g1A5CI07AYCUo7GSOH3X78lD8fdu/NMakh+GB9o/AgH2iCvlZhOWnQ8efh+XJIG6TQTAp0d0bM5WNXWRGad8rPiqwHGmsRF3lwAFzhjHYmTqELmDCX0+LBXRv4FnZf3x1n4C6QpTNY0W7eCqixOP5n+PS36oYskPlQFT0i2Ei8Sc8MUYRb7CWn0pqkbkc/bVRtBu3CnksXCefR5e/lFB90Y+mirSsxVVvU2eacKtLo/lZPZZraiqwZqC9oEpktZex1OrEYl/MjYYRnO5q/+zCQnfsxRw4H8RVd7xwM1zIG2cwRgg8WBDMeCEN1JmFOGxigHwY+2dQjotshnQDpeKoW+k/N8LjHcZcgyAeIb+roTn/R4LKwh9wwABY/6SdZaaidkO4buf3R9aEy4R51VlxLKYD8+VkpuUBaY/cEzXsVEBrxkXswoSgoMESh1GmGuQ0oQorXVGEQdmFJnTAFxTd0cP98hqC7luH7umwDYRT4GAul6Xo1qGI+XYcjRYwM92Oy1v8LA671t9tq5RkfheK9y7mL950zUHsXG/X497kve2ip5fC8ihI="
    on_success: always
    on_failure: always

before_install: source scripts/ci/environment.sh

install: docker build -t $DOCKER_IMAGE .

script: true

after_success:
- ci-tag-build
- hub-push
