language: python
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "5AJgm9BX4RMsVTKJZMwvrSYrhlGAh2F1bF289PtrAP7BqJ80czo/6zs2dkYcNfWmL21E7g+VjyNW9YZ4gBtB+Vcge/DBYJDXIpfj79JXgqgF+v4NeLS7mrAANYSYeOzii9sPWvMQOmjDuYsJwgpDV3HoNzrVGRwg1a6dKg/p7ifB2HY16low3zm/ZakRsNltf0q7KMhgSq/aU5uajk4jf8KGuqbLA+L76N6mdTDT+UZNvMGCHiyUASx12OZtx7vsnhoS2GXLFd9GI27fB0eVcGZ5PkgXe+rdHPLeojee4781vv5+b/paaiYexKqs2BzRiEd0LcEDS7LOnFYaPCgEcb++ly8i80iDDEMLdvvP3ir9w6EA40hvdKt/yGfMla95QvF+JMMuPjd8mSkAWifEhvgVL5Ut4fMkb2jxblz9FHhkw9uPj8I7j21FND4lzL5nMaBFTd3RLz1QpgIwVWPG9pTSB8fqp3Sf2DBLYO3hKziZQrh1xzWSAFvZwwRSW0JxiQYdjdwA89PU2JlN4lqmpDUG9s8w83zR3V1yPi+DNZCCokurPu8g/r0BoAdgW14z7Dz62aMEwgrZJZvwLlGPIM6E1tBpjxZD3lqZTsz6ZxjYPdXWfUv0FqU7QCxoVQzVcpjwJcxUMBFqyohf9Ewnm8B/kcQ4nv/bCa5HgLja7zE="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "21z2YTUBZyeA1Bf54TdOMNp/z102FqD2CLAyjQZK4piTZT11vcFTOgKKbnzzNLO09mgfNmnkPJQSLuNXqQgxjBS8+osYBSQnMxve8gigDiTnhIjZ8tTZM+g1A5CI07AYCUo7GSOH3X78lD8fdu/NMakh+GB9o/AgH2iCvlZhOWnQ8efh+XJIG6TQTAp0d0bM5WNXWRGad8rPiqwHGmsRF3lwAFzhjHYmTqELmDCX0+LBXRv4FnZf3x1n4C6QpTNY0W7eCqixOP5n+PS36oYskPlQFT0i2Ei8Sc8MUYRb7CWn0pqkbkc/bVRtBu3CnksXCefR5e/lFB90Y+mirSsxVVvU2eacKtLo/lZPZZraiqwZqC9oEpktZex1OrEYl/MjYYRnO5q/+zCQnfsxRw4H8RVd7xwM1zIG2cwRgg8WBDMeCEN1JmFOGxigHwY+2dQjotshnQDpeKoW+k/N8LjHcZcgyAeIb+roTn/R4LKwh9wwABY/6SdZaaidkO4buf3R9aEy4R51VlxLKYD8+VkpuUBaY/cEzXsVEBrxkXswoSgoMESh1GmGuQ0oQorXVGEQdmFJnTAFxTd0cP98hqC7luH7umwDYRT4GAul6Xo1qGI+XYcjRYwM92Oy1v8LA671t9tq5RkfheK9y7mL950zUHsXG/X497kve2ip5fC8ihI="
    on_success: always
    on_failure: always

before_install: source scripts/ci/environment.sh

install: docker build -t $DOCKER_IMAGE .

script: true

after_success:
- ci-tag-build
- hub-push
